const PATH = {
	CONTROL_PANEL:'/admin/control-panel',
	NEWSLETTER:'/Newsletter',
	COUPON_REQUREST_OFFER:'/submit',
	ABOUT_US:'/about-us',
	TERM_AND_CONDITIONS:'/terms-conditions',
	UPDATE_CATEGORY:'/update-category/:id',
	UPDATE_USER:'/update-user/:id',
	UPDATE_ABOUT_PAGE:'/update/about-page',
	USER_BLOGS:'/blog/all',
	USER_COUPONS:'/coupon/all',
	USER_STORES:'/my/stores',
	COUPON_REQUREST:'/request/coupon',
	STORE_REQUREST:'/request/store',
	BLOG_REQUREST:'/request/blog',
	ABOUT_PAGE: "/about-page",
	LANDING_PAGE_ADMIN_EDIT: "/landing-page/edit",
	LANDING_PAGE: "/",
	NOPAGE: "*",
	CLOSED: "/closed",
	CREATE_USER:'/create-user',
	MANAGE_PRODUCTS:'/product/list',
	ADD_PRODUCT:'/product/add',
	VIEW_PRODUCT:'/product/view',
	EDIT_PRODUCT:'/product/edit',
	MANAGE_COUPONS:'/coupon/list',
	ADD_COUPONS:'/coupon/add',
	UPDATE_COUPONS:'/coupon/update/:id',
	EDIT_PRIVACY_POLICY:'/edit-privacy-policy',
	EDIT_TERMS_CONDITIONS:'/edit-terms-conditions',

	//  AUTH PATHS
	LOGIN: "/login",
	SIGNUP: "/signup",
	INSTITUTE_SIGNUP: "/institute/signup",
	FORGOT_PASSWORD: "/forgot-password",
	UPDATE_PASSWORD: "/update-password",
	OTP_SCREEN: "/otp-screen",


	ADMIN_PROFILE: "/profile",
	INSTITUTE_SETTINGS: "/institute/settings",
	MANAGE_USERS: "/user/list",
	MANAGE_OPRATION: "/operation/list",
	MANAGE_OPRATION_CREATE: "/manage-operation/create",
	MANAGE_OPRATION_UPDATE: "/manage-operation/update",
	STORES: "/store/list",
	ADD_STORES: "/create/store",
	COURSE_VIEW: "/course/view/:id",
	COURSE_VIEW_STUDENT: "/student/course/view/:id",
	NEW_COURSE: "/course/create",

	ITEM_DASHBOARD: "/item-dashboard",
	CARD_DASHBOARD: "/card-dashboard",
	SAVED_CARDS: "/saved-card",
	PREPARE_CARDS: "/prepare-card",
	PREPARE_CARD_EDIT: "/prepare-card/:id/edit",
	MY_KEYS: "/my-keys",
	SIGNED_CARDS: "/signed-cards",
	SIGNED_CARD_EDIT: "/signed-card/:id/edit",
	SIGNED_CARD_PUBLISH_ITEMS: "/signed-card/:id/publish-items",

	//Teacher
	MANAGE_TEACHER: "/manage-teacher/list",
	STUDENTS: "/student/list",
	MANAGE_TEACHER_CREATE: "/manage-teacher/create",
	TEACHER_PROFILE: "/teacher-profile/:id",
	ADMIN_DASHBOARD: "/admin-dashboard",
	USER_DASHBOARD: "/user-dashboard",
	TEACHER_STUDENT_PROFILE_VIEW: "/teacher/student-profile-view/:id",

	//Finance
	COUPONS: "/finance/coupons",
	REGISTRATION_REQUEST: "/request/registration",
	COURSE_REQUEST: "/request/courses",
	COUPONS_CREATE: "/finance/coupons/create",
	EARNINGS: "/finance/earnings",
	VIEW_EARNINGS: "/finance/earnings/view/:id",
	STUDENTS_EARNINGS: "/finance/students-earnings/view/:id",

	//Students
	STUDENT_PROFILE: "/student/info/:tab",
	STUDENT_DASHBOARD: "/student/dashboard",
	STUDENT_COURSE_VIEW: "/student/course/:id/view",
	STUDENT_COURSES_LIST: "/student/courses",
	STUDENT_ASSIGNMENTS: "/student/assignments",
	STUDENT_QUIZZES: "/student/quizzes",
	STUDENT_GRADE_ASSIGNMENTS: "/student/grade/assignments",
	STUDENT_GRADE_QUIZZES: "/student/grade/quizzes",
	STUDENT_ENROLLED_COURSES: "/opration/list",
	SINGLE_STORE:'/coupons/:id',
	SINGLE_CATEGORY:'/category/:id',
	ALL_CATEGORY:'/category/all',
	VIEW_BLOG:'/allblog/view',
	ALL_BLOG:'/blogs',
	SINGLE_BLOG:'/blog/:id',
	ADD_BLOGS:'/addblog/add',
	UPDATE_BLOG:'/update-blog/:id',
	VIEW_CATEGORY:'/category/view',
	ADD_CATEGORY:'/category/add',
	VIEW_NETWORK:'/network/view',
	ADD_NETWORK:'/network/add',
	UPDATE_NETWORK:'/update-network/:id',
	VIEW_DEALS:'/deals/add',
	VIEW_EVENTS:'/event/all/view',
	ADD_EVENT:'/event/add',
	EDIT_EVENT:'/event/edit/:id',
	SINGLE_EVENT:'/seasonal/:id',
	TERMS_CONDITIONS:'/terms-conditions-admin',
	PRIVACY_POLICY:'/privacyPolicy',
	PRIVACY_POLICY_LANDING:'/privacy-policy',
	CONTACT_FORM:'/contact',
	SHIPPING_PAGE:'/free-shipping',
	SHIPPING_PAGE_ALL:'/shipping/all',
	ADD_SHIPPING_PAGE:'/shipping/add',
	STORE:'/store/all',
	LANDING_PAGE_ADMIN:'/landing-page',
};

export default PATH;
